name: Publish to NPM  # 工作流名称：发布到NPM

on:
  release:
    types: [created]  # 触发条件：当创建新的发布版本时

jobs:
  build-and-publish:  # 工作名称：构建并发布
    runs-on: ubuntu-latest  # 运行环境：最新的Ubuntu

    steps:
    - name: Checkout code  # 步骤名称：检出代码
      uses: actions/checkout@v3  # 使用actions/checkout@v3来检出代码

    - name: Set up Node.js 18  # 步骤名称：设置Node.js 18
      uses: actions/setup-node@v3  # 使用actions/setup-node@v3来设置Node.js环境
      with:
        node-version: '18'  # 指定Node.js版本为18

    - name: Install dependencies  # 步骤名称：安装依赖
      run: npm install  # 运行npm install来安装项目依赖

    - name: Build  # 步骤名称：构建
      run: npm run build  # 运行npm run build来构建项目

    - name: Publish to NPM  # 步骤名称：发布到NPM
      uses: JS-DevTools/npm-publish@v1  # 使用JS-DevTools/npm-publish@v1来发布到NPM
      with:
        token: ${{ secrets.NPM_TOKEN }}  # 使用GitHub仓库的secrets中的NPM_TOKEN
        registry: https://registry.npmjs.org  # 指定NPM注册表地址

    - name: Deprecate all previous versions  # 步骤名称：废弃所有历史版本
      run: npm deprecate cx-flow@<0.0.10